In [1]:
from scipy.io import loadmat
import pandas as pd

sub1_test_label = loadmat('sub1_testlabels.mat')
sub1_test_label_arr = sub1_test_label["test_dg"]

In [2]:
sub1_test_label_df = pd.DataFrame(sub1_test_label_arr, columns = ['F1','F2','F3', 'F4', 'F5'])

In [3]:
feature_names_normal = ['F1_N', 'F2_N', 'F3_N', 'F4_N', 'F5_N']
feature_names_dropped = ['F1_D', 'F2_D', 'F3_D', 'F4_D', 'F5_D']

In [4]:
predictions1 = pd.read_csv("/Users/soumilhooda/Desktop/BCI/outputSub1_test.ascii", delim_whitespace=True, header=None)
predictions1.columns = feature_names_normal

predictions2 = pd.read_csv("/Users/soumilhooda/Desktop/BCI/outputSub1_drop54_test.ascii", delim_whitespace=True, header=None)
predictions2.columns = feature_names_dropped

In [5]:
F1_N_Pred = predictions1[['F1_N']]
F2_N_Pred = predictions1[['F2_N']]
F3_N_Pred = predictions1[['F3_N']]
F4_N_Pred = predictions1[['F4_N']]
F5_N_Pred = predictions1[['F5_N']]

F1_D_Pred = predictions2[['F1_D']]
F2_D_Pred = predictions2[['F2_D']]
F3_D_Pred = predictions2[['F3_D']]
F4_D_Pred = predictions2[['F4_D']]
F5_D_Pred = predictions2[['F5_D']]

F1_Actual = sub1_test_label_df[['F1']]
F2_Actual = sub1_test_label_df[['F2']]
F3_Actual = sub1_test_label_df[['F3']]
F4_Actual = sub1_test_label_df[['F4']]
F5_Actual = sub1_test_label_df[['F5']]

In [6]:
F1_N_Pred_arr = F1_N_Pred.to_numpy()
F2_N_Pred_arr = F2_N_Pred.to_numpy()
F3_N_Pred_arr = F3_N_Pred.to_numpy()
F4_N_Pred_arr = F4_N_Pred.to_numpy()
F5_N_Pred_arr = F5_N_Pred.to_numpy()

F1_D_Pred_arr = F1_D_Pred.to_numpy()
F2_D_Pred_arr = F2_D_Pred.to_numpy()
F3_D_Pred_arr = F3_D_Pred.to_numpy()
F4_D_Pred_arr = F4_D_Pred.to_numpy()
F5_D_Pred_arr = F5_D_Pred.to_numpy()

F1_Actual_arr = F1_Actual.to_numpy()
F2_Actual_arr = F2_Actual.to_numpy()
F3_Actual_arr = F3_Actual.to_numpy()
F4_Actual_arr = F4_Actual.to_numpy()
F5_Actual_arr = F5_Actual.to_numpy()

In [9]:
import numpy as np
from scipy.stats.stats import pearsonr  


print(np.corrcoef(F1_Actual_arr, F1_N_Pred_arr, rowvar=False))
print(np.corrcoef(F1_Actual_arr, F1_D_Pred_arr, rowvar=False))
print("\n")
print(np.corrcoef(F2_Actual_arr, F2_N_Pred_arr, rowvar=False))
print(np.corrcoef(F2_Actual_arr, F2_D_Pred_arr, rowvar=False))
print("\n")
print(np.corrcoef(F3_Actual_arr, F3_N_Pred_arr, rowvar=False))
print(np.corrcoef(F3_Actual_arr, F3_D_Pred_arr, rowvar=False))
print("\n")
print(np.corrcoef(F4_Actual_arr, F4_N_Pred_arr, rowvar=False))
print(np.corrcoef(F4_Actual_arr, F4_D_Pred_arr, rowvar=False))
print("\n")
print(np.corrcoef(F5_Actual_arr, F5_N_Pred_arr, rowvar=False))
print(np.corrcoef(F5_Actual_arr, F5_D_Pred_arr, rowvar=False))



[[1.         0.06715516]
 [0.06715516 1.        ]]
[[1.         0.05043609]
 [0.05043609 1.        ]]


[[1.         0.03275503]
 [0.03275503 1.        ]]
[[1.         0.01781161]
 [0.01781161 1.        ]]


[[1.         0.04340157]
 [0.04340157 1.        ]]
[[1.        0.0531663]
 [0.0531663 1.       ]]


[[1.         0.03787393]
 [0.03787393 1.        ]]
[[1.         0.03733196]
 [0.03733196 1.        ]]


[[1.         0.04367895]
 [0.04367895 1.        ]]
[[1.         0.05577002]
 [0.05577002 1.        ]]
