In [1]:
import numpy as np
from pandas import read_csv
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasRegressor
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from keras.models import model_from_json


Using TensorFlow backend.


In [8]:
from scipy.io import loadmat

sub1_train_data = loadmat('train_data_sub1.mat')
sub1_train_label = loadmat('train_label_sub1.mat')
sub1_test_data = loadmat('test_data_sub1.mat')

# sub2_train_data = loadmat('train_data_sub2.mat')
# sub2_train_label = loadmat('train_label_sub2.mat')

# sub3_train_data = loadmat('train_data_sub3.mat')
# sub3_train_label = loadmat('train_label_sub3.mat')

sub1_train_data_arr = sub1_train_data["train_data"]
sub1_train_label_arr = sub1_train_label["train_dg"]
sub1_test_data_arr = sub1_test_data["test_data"]

# sub2_train_data_arr = sub2_train_data["train_data"]
# sub2_train_label_arr = sub2_train_label["train_dg"]

# sub3_train_data_arr = sub3_train_data["train_data"]
# sub3_train_label_arr = sub3_train_label["train_dg"]

In [10]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(sub1_train_data_arr)
X_train_scaled = scaler.transform(sub1_train_data_arr)
X_test_scaled = scaler.transform(sub1_test_data_arr)

In [11]:
model = Sequential()
model.add(Dense(512, input_dim=62, activation='sigmoid'))
model.add(Dense(256, activation='sigmoid'))
model.add(Dense(128, activation='sigmoid'))
#Output layer
model.add(Dense(5, activation='linear'))

model.compile(loss='mean_squared_error', optimizer='adam', metrics=['mae'])
model.summary()

history = model.fit(X_train_scaled, sub1_train_label_arr, validation_split=0.1, epochs=20)

loss = history.history['loss']
print(loss)
np.savetxt('loss_testSub1.ascii',(loss))

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_13 (Dense)             (None, 512)               32256     
_________________________________________________________________
dense_14 (Dense)             (None, 256)               131328    
_________________________________________________________________
dense_15 (Dense)             (None, 128)               32896     
_________________________________________________________________
dense_16 (Dense)             (None, 5)                 645       
Total params: 197,125
Trainable params: 197,125
Non-trainable params: 0
_________________________________________________________________
Train on 360000 samples, validate on 40000 samples
Epoch 1/20
360000/360000 [==============================] - 114s 316us/step - loss: 0.9011 - mae: 0.5535 - val_loss: 0.9810 - val_mae: 0.5797
Epoch 2/20
360000/360000 [===========================

In [12]:
predictions = model.predict(X_test_scaled)
print("Predicted values are: ", predictions)
# print("Real values are: ", y_test)
# np.savetxt ('output1_test.ascii',(y_test))
np.savetxt ('outputSub1_test.ascii',(predictions))
# mse_neural, mae_neural = model.evaluate(X_test_scaled, y_test)
# print('Mean squared error from neural net: ', mse_neural)
# print('Mean absolute error from neural net: ', mae_neural)

Predicted values are:  [[-0.22667249 -0.06628439 -0.35340208 -0.2375992  -0.17269264]
 [-0.25059804 -0.06803401 -0.33050206 -0.24354106 -0.14105013]
 [-0.31811675 -0.09856722 -0.31808904 -0.26377383 -0.10976262]
 ...
 [-0.08145961 -1.0859782  -0.747926   -0.78364384 -0.6662502 ]
 [-0.07030082 -1.1093915  -0.7580338  -0.78708994 -0.69435996]
 [-0.06677401 -1.1184858  -0.7522591  -0.7831124  -0.712768  ]]


In [13]:
model_json = model.to_json()
with open("modelSub1_test.json", "w") as json_file:
    json_file.write(model_json)
        # serialize weights to HDF5
    model.save_weights("modelSub1_test.h5")
    print("Saved model to disk")

Saved model to disk


In [14]:
sub1_test_label = loadmat('sub1_testlabels.mat')
sub1_test_label_arr = sub1_test_label["test_dg"]

In [ ]:
# print(np.corrcoef(predictions, sub1_test_label_arr))
print(predictions[0:10])